module.exports = {
  WALKERS: 'WALKERS',
  ROUTE_LEADER: 'ROUTE_LEADER',
  EMERGENCY_VOLUNTEER: 'EMERGENCY_VOLUNTEER',
  HOST: 'HOST',
  SOUP: 'SOUP',
  EGGS: 'EGGS',
  TUNA_SANDWICHES: 'TUNA_SANDWICHES',
  CHEESE_SANDWICHES: 'CHEESE_SANDWICHES',
  FRUIT: 'FRUIT',
  COOKIES: 'COOKIES',
  JUICES: 'JUICES',
}